# Generated by Django 5.1.3 on 2024-11-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_orderdetails_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='address',
            field=models.CharField(default='null', max_length=250),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='full_name',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='mobile_number',
            field=models.CharField(default='null', max_length=15),
        ),
    ]
