# Generated by Django 5.1.3 on 2024-11-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_orderitem_address_orderitem_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='address',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='mobile_number',
            field=models.CharField(max_length=15),
        ),
    ]
