# Generated by Django 5.1.3 on 2024-11-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_buyer_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='address',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='contact_number',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
