# Generated by Django 5.1.3 on 2024-11-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_customeraddress_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='city',
            field=models.CharField(max_length=50),
        ),
    ]
