# Generated by Django 5.1.3 on 2024-11-09 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_buyer_address_alter_buyer_contact_number'),
        ('checkout', '0003_alter_customeraddress_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16)),
                ('expire_date', models.CharField(max_length=4)),
                ('cvv', models.CharField(max_length=3)),
                ('pincode', models.CharField(max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='accounts.buyer')),
            ],
        ),
    ]
